import "./Help.css";
import statistics from "/src/img/Favicon/favicon_io/statistics.png";
import stocks from "/src/img/Favicon/favicon_io/stocks.png";
import column_1 from "/src/img/Favicon/favicon_io/column_1.png";
import column_2 from "/src/img/Favicon/favicon_io/column_2.png";
import billing_1 from "/src/img/Favicon/favicon_io/billing_1.png";
const Help = () => {
  return (
    <div className="wrapper_help">
      <div className="main_content_help">
        <div className="header_help">Help</div>
        <div className="info_help">
          <div className="faqs_help">
            <div className="faqs_title">FAQs</div>
            <div className="faqs_content">
            We're here to support you every step of the way. If you have any questions or need assistance, feel free to ask!
              <ul className="faq">
                <li className="faq_bullet">
                  How to add new column to the table ?
                </li>
                <li className="faq_bullet">aaaaaaaaaaaaaaaaaaaa ?</li>
              </ul>
            </div>
          </div>
          <div className="statistics_help">
            <div className="statistics_head_help">Statistics Page</div>
            <img
              src={statistics}
              alt="Statistics"
              className="statistics-style"
            />

            <div className="statistics_intro_help">
              <p>
                Welcome to the statistics webpage of our shop! This page is
                designed to provide you with valuable insights into the
                performance of your shop and help you make informed
                decisions.Let us take a closer look at the different features of
                this page :
              </p>

              <ul className="statistics_text_help">
                <li>
                  <div className="subhead_help"> Total Order:</div>
                  This section displays the total number of orders placed by
                  customers. It gives you an overview of the overall sales
                  volume and customer demand. By tracking this metric, you can
                  assess the popularity of your products ,benchmark your performance and forecast future sales.
                </li>

                <li>
                  <div className="subhead_help"> Total Profit:</div>
                  In this section, you can see the total profit generated by
                  your shop. It takes into account the revenue from sales .
                  Monitoring your profit allows you to assess the financial
                  health of your business and make strategic decisions to
                  optimize profitability.
                </li>

                <li>
                  <div className="subhead_help"> Total Expense:</div>
                  This section shows the total expenses incurred by your shop.
                  Tracking your
                  expenses helps you understand where your money is being
                  allocated and identify areas where you can potentially reduce
                  costs.
                </li>

                <li>
                  <div className="subhead_help">
                    {" "}
                    Products Nearing Expiry Date:
                  </div>
                  Here, you will find a list of products that are approaching
                  their expiration date. This feature is crucial for managing
                  inventory and minimizing waste. By identifying these products,
                  you can take proactive steps such as offering discounts or
                  promotions to encourage their sale or planning their timely
                  restocking to ensure freshness and avoid losses.
                </li>

                <li>
                  <div className="subhead_help">
                    {" "}
                    Products to be Restocked:
                  </div>
                  In this section, you will find a list of products that need to
                  be restocked soon. It helps you maintain sufficient stock
                  levels to meet customer demand and prevent stockouts. By
                  keeping an eye on this information, you can ensure that
                  popular products are readily available and avoid missed sales
                  opportunities.
                </li>
              </ul>
            </div>
          </div>
          <div className="stocks_help">
            <div className="stocks_head_help">Stock Page</div>
            <img src={stocks} alt="Stocks" className="stocks-style" />
            <div className="stocks_intro_help">
            Introducing the Stocks Webpage . This pge is designed to empower you with complete control over your shop's product data and inventory status. Whether you want to explore existing stock details, add new products, or update quantities after each purchase, this user-friendly interface has got you covered Let's explore the features and functionalities of this page:
            </div>
            <div className="stocks_text_help">
              <ul>
                <li><div className="subhead_help">
                Product Data Overview : </div>
                The page displays a comprehensive list of products currently in stock at your shop. It includes essential details such as the product name, description, price, quantity available, and any other relevant information. This overview helps you quickly assess the inventory and understand the range of products you offer.
                </li>
                <li>
                  <div className="subhead_help">Add New Product</div>
                  This is an option provided to add new products to the stock list.Seamlessly expand your stock list by leveraging the "Add" feature. This intuitive option allows you to effortlessly input details such as product name, description, price, and initial quantity, ensuring that your inventory stays up to date with the latest additions.
                </li>
              </ul>
              This keeps your inventory accurate and reliable by promptly updating stock after each purchase.Take advantage of this robust features to effectively organize your stock, add new products, maintain accurate quantities swiftly.
            </div>
          </div>


          <div className="billing_help">
            <div className="billing_help_head">Billing</div>
            <img src={billing_1} className="billing_1" />
            <div className="billing_help_content">
              <div className="billing_help_content_subhead"></div>
            </div>
          </div>
          <div className="column_help">
            <div className="column_help_head">Columns</div>
            <div className="column_help_pics">
              <img src={column_1} className="column_1" />
              <img src={column_2} className="column_1" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Help;
