import "./Help.css";
import statistics from "/src/img/Favicon/favicon_io/statistics.png";
import stocks from "/src/img/Favicon/favicon_io/stocks.png";
const Help = () => {
  return (
    <div className="wrapper_help">
      <div className="main_content_help">
        <div className="header_help">Help</div>
        <div className="info_help">
          <div className="faqs_help">
            <div className="faqs_title">FAQs</div>
            <div className="faqs_content">
              <ul className="faq">
                <li className="faq_bullet">How to add new column to the table ?</li>
                <li className="faq_bullet">aaaaaaaaaaaaaaaaaaaa ?</li>
              </ul>
            </div>
          </div>
          <div className="statistics_help">
            <div className="statsiticshead_help">Statistics Page</div>
            <img
              src={statistics}
              alt="Statistics"
              className="statistics-style"
            />

            <div className="statistics_intro_help">
              <p>
                Welcome to the statistics webpage of our shop! This page is
                designed to provide you with valuable insights into the
                performance of your shop and help you make informed
                decisions.Let us take a closer look at the different features of
                this page :
              </p>

              <ul className="statistics_text_help">
                <li>
                  <div className="subhead1_help"> Total Order:</div>
                  This section displays the total number of orders placed by
                  customers. It gives you an overview of the overall sales
                  volume and customer demand. By tracking this metric, you can
                  assess the popularity of your products and identify any trends
                  or patterns.
                </li>

                <li>
                  <div className="subhead1_help"> Total Order:</div>
                  In this section, you can see the total profit generated by
                  your shop. It takes into account the revenue from sales minus
                  the cost of goods sold and any other associated expenses.
                  Monitoring your profit allows you to assess the financial
                  health of your business and make strategic decisions to
                  optimize profitability.
                </li>

                <li>
                  <div className="subhead1_help"> Total Order:</div>
                  This section shows the total expenses incurred by your shop.
                  It includes costs such as inventory, utilities, wages,
                  marketing, and other operational expenses. Tracking your
                  expenses helps you understand where your money is being
                  allocated and identify areas where you can potentially reduce
                  costs.
                </li>

                <li>
                  <div className="subhead1_help"> Total Order:</div>
                  Here, you will find a list of products that are approaching
                  their expiration date. This feature is crucial for managing
                  inventory and minimizing waste. By identifying these products,
                  you can take proactive steps such as offering discounts or
                  promotions to encourage their sale or planning their timely
                  restocking to ensure freshness and avoid losses.
                </li>

                <li>
                  <div className="subhead1_help"> Total Order:</div>
                  In this section, you will find a list of products that need to
                  be restocked soon. It helps you maintain sufficient stock
                  levels to meet customer demand and prevent stockouts. By
                  keeping an eye on this information, you can ensure that
                  popular products are readily available and avoid missed sales
                  opportunities.
                </li>
              </ul>
            </div>
          </div>
          <div className="stocks_help">
            <div className="stockshead_help">
              Stock Page
            </div>
            <img src={stocks}  alt="Stocks" className="stocks-style" />
          </div>
          <div className="column_help">
            <div className="column_help_head">Columns</div>

          </div>
        </div>
      </div>
    </div>
  );
};
export default Help;
