import "./Help.css";
import statistics from "./Help_pics/statistics.png";
import stocks1 from "./Help_pics/Stocks1.png";
import stocks2 from "./Help_pics/Stocks2.png";
import column_1 from "./Help_pics/column_1.png";
import billing_1 from "./Help_pics/billing_1.png";
const Help = () => {
  return (
    <div className="wrapper_help">
      <div className="main_content_help">
        <div className="header_help">Help</div>
        <div className="info_help">
          <div className="statistics_help">
            <div className="head_help">Statistics</div>
            <img
              src={statistics}
              alt="Statistics"
              className="statistics-style"
            />

            <div className="intro_help">
              <p>
                Welcome to the statistics webpage of our shop ! This page is
                designed to provide you with valuable insights into the
                performance of your shop and help you make informed
                decisions.Let us take a closer look at the different features of
                this page :
              </p>

              <ul className="text_help">
                <li className="text_child_help">
                  <div className="subhead_help"> Total Order</div>This section displays the total number of orders placed by customers. It gives you an overview of the overall sales
                  volume and customer demand. By tracking this metric, you can
                  assess the popularity of your products ,benchmark your
                  performance and forecast future sales.
                </li>

                <li className="text_child_help">
                  <div className="subhead_help"> Total Profit</div>
                  In this section, you can see the total profit generated by
                  your shop. It takes into account the revenue from sales .
                  Monitoring your profit allows you to assess the financial
                  health of your business and make strategic decisions to
                  optimize profitability.
                </li>

                <li className="text_child_help">
                  <div className="subhead_help"> Total Expense</div>
                  This section shows the total expenses incurred by your shop.
                  Tracking your expenses helps you understand where your money
                  is being allocated and identify areas where you can
                  potentially reduce costs.
                </li>

                <li className="text_child_help">
                  <div className="subhead_help">
                    Products Nearing Expiry Date
                  </div>
                  Here, you will find a list of products that are approaching
                  their expiration date. This feature is crucial for managing
                  inventory and minimizing waste. By identifying these products,
                  you can take proactive steps such as offering discounts or
                  promotions to encourage their sale or planning their timely
                  restocking to ensure freshness and avoid losses.
                </li>

                <li className="text_child_help">
                  <div className="subhead_help">
                    {" "}
                    Products to be Restocked
                  </div>
                  In this section, you will find a list of products that need to
                  be restocked soon. It helps you maintain sufficient stock
                  levels to meet customer demand and prevent stockouts. By
                  keeping an eye on this information, you can ensure that
                  popular products are readily available and avoid missed sales
                  opportunities.
                </li>
              </ul>
            </div>
          </div>
          <div className="stocks_help">
            <div className="head_help">Stocks</div>
            <img src={stocks1} alt="Stocks" className="stocks-style" />
            <div className="intro_help">
            Introducing the Stocks Webpage . This pge is designed to empower you with complete control over your product data and inventory status. Whether you want to explore existing stock details, add new products, or update quantities after each purchase, this user-friendly interface has got you covered Let us explore the features and functionalities of this page:
              <ul className="text_help">
                <li className="text_child_help"><div className="subhead_help">
                Product Data Overview  </div>
                The page displays a comprehensive list of products currently in stock at your shop. It includes essential details such as the product name, description, price, quantity available, and any other relevant information. This overview helps you quickly assess the inventory and understand the range of products you offer.
                </li></ul>
                <img src={stocks2} alt="Stocks" className="stocks-style" />
                <ul className="text_help">
                <li className="text_child_help">
                  <div className="subhead_help">Add New Product</div>
                  This is an option provided to add new products to the stock
                  list.Seamlessly expand your stock list by leveraging the Add
                  feature. This intuitive option allows you to effortlessly
                  input details such as product name, description, price, and
                  initial quantity, ensuring that your inventory stays up to
                  date with the latest additions.
                </li>
              </ul>
              This keeps your inventory accurate and reliable by promptly
              updating stock after each purchase.Take advantage of this robust
              features to effectively organize your stock, add new products,
              maintain accurate quantities swiftly.
            </div>
          </div>

          <div className="billing_help">
            <div className="statistics_head_help">Billing Page</div>
            <img src={billing_1} className="billing_1" />
            <ul className="billing_help_content">
              <li className="billing_help_content_child">
                The billing page is where you can easily create and print
                invoices for your customers purchases.
              </li>
              <li className="billing_help_content_child">
                To add items to the invoice, simply enter the serial number and
                quantity of each product in the provided columns and click the
                Add button.
              </li>
              <li className="billing_help_content_child">
                The respective item will be added to the table. Repeat this
                process for all the required products.
              </li>
              <li className="billing_help_content_child">
                Once you have added all the items to the invoice, you can easily
                calculate the total amount. The page will automatically sum up
                the individual item prices and display the total amount. This
                ensures accurate and efficient billing for your customers.
              </li>
            </ul>
          </div>
          <div className="column_help">
            <div className="statistics_head_help">Columns Page</div>
            <img src={column_1} className="column_1" />
            <ul className="billing_help_content">
              <li className="billing_help_content_child">
                One of the major features of this website is the ability to
                customize columns. The Columns page allows you to easily add new
                columns to the table according to your specific requirements.
              </li>
              <li className="billing_help_content_child">
                To add a new column, simply enter the desired column name in the
                provided field. Then, select the type of value that the column
                should contain from the dropdown menu. The dropdown menu
                provides various options such as text, number or date.
              </li>
              <li className="billing_help_content_child">
                After entering the column name and selecting the data type,
                click the Add Column button. This action instantly adds the new
                column to the table, enabling you to store and manage data of
                that specific type.
              </li>
              <li className="billing_help_content_child">
                This feature provides flexibility and customization, allowing
                you to tailor the table structure to suit your specific needs.
              </li>
              <li className="billing_help_content_child">
                With the customizable columns feature, you can easily adapt the
                table to accommodate different types of data, ensuring a more
                efficient and personalized experience for managing your
                information.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Help;
